name: CI

on:
  push:
    branches:
      - master
      - release**
  pull_request:
    branches:
      - master
      - release**

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - name: Print branch name
      run: |
        echo "Current branch name: ${{ github.ref_name }}"
        echo "Current build number: ${{ github.run_number }}"
