name: CI

on:
  push:
    branches:
      - master
    tags:
      - rel-*
  pull_request:
    branches:
      - master

jobs:
 prep-build:
  runs-on: windows-2019
  env: 
      BRANCH_NAME: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}
      COMMIT_HASH: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      RELEASE_BUILD: ${{ startsWith(github.ref, 'refs/tags/try') && true || false }}
  outputs:
    branch_name: ${{ env.BRANCH_NAME }}
    commit_hash: ${{ env.COMMIT_HASH }}
    release_build: ${{ env.RELEASE_BUILD }}
  steps:
    - uses: actions/checkout@v2
   
    - name: Print build env
      run: |
        echo "BRANCH_NAME: ${{ env.BRANCH_NAME }}"
        echo "COMMIT_HASH: ${{ env.COMMIT_HASH }}"
        echo "RELEASE_BUILD: ${{ env.RELEASE_BUILD }}"

    - name: Add PR Comment
      uses: actions/github-script@v5
      if: ${{ github.event_name == 'pull_request' }}
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Current build number: ${{ env.BRANCH_NAME }}'
          })

 run-build:
  runs-on: windows-2019
  needs: prep-build
  steps:
    - name: Verify env
      run: |
        echo "branch_name: ${{ needs.prep-build.outputs.branch_name }}"
        echo "commit_hash: ${{ needs.prep-build.outputs.commit_hash }}"
        echo "release_build: ${{ needs.prep-build.outputs.release_build }}"
    
